[package]
name = "rust_competitive_helper"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
dialoguer = "~0.9"
chrono = "~0.4"
itertools = "~0.10"
